VANILLA_DIR = $(BSG_MANYCORE_DIR)/imports/vanilla-bean
BSG_IP_CORES_DIR = $(BSG_MANYCORE_DIR)/../bsg_ip_cores
BERKELEY_HARDFLOAT_DIR = $(BSG_MANYCORE_DIR)/../berkeley-hardfloat
# Shunning: use the locally installed riscv gcc
# RISCV_BIN_DIR = $(BSG_MANYCORE_DIR)/software/riscv-tools/riscv-install/bin
RISCV_BIN_DIR = $(BARE_PKGS_GLOBAL_PREFIX)/bsg_manycore_tools/riscv-install/bin
CAD_DIR = $(BSG_MANYCORE_DIR)/../bsg_cadenv

